version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Example: Specify a runtime if needed
    commands:
      - echo "Installing dependencies (if any)..."
      # Install zip utility if not already available
      - yum install -y zip

  pre_build:
    commands:
      - echo "Preparing files for zipping..."
      # Create a directory if needed to organize the output
      - mkdir -p output

  build:
    commands:
      - echo "Zipping files..."
      # Replace 'source_folder' with your actual folder containing the files to zip
      - zip -r output/deployment-package.zip source_folder
      - echo "Zipping completed. Deployment package created at output/deployment-package.zip"

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - output/deployment-package.zip # Specify the zip file to be retained as an artifact
  discard-paths: yes # Keeps only the zip file, not the full path structure
