version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Specify the runtime (e.g., Node.js, Python, etc.)
    commands:
      - echo "Installing dependencies..."
      - yum install -y zip  # Install zip tool if required for packaging

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - echo "Validating HTML..."
      - curl -s https://validator.w3.org/nu/ -F "out=json" -F "content=$(cat index.html)"

  build:
    commands:
      - echo "Building the deployment package..."
      - zip -r my-deployment-package.zip index.html appspec.yml scripts/

  post_build:
    commands:
      - echo "Uploading deployment package to S3..."
      - aws s3 cp my-deployment-package.zip s3://your-s3-bucket-name/

artifacts:
  files:
    - my-deployment-package.zip
